In [ ]:
RAW_DATA_PATH = "/content/drive/MyDrive/Chotot Project/RawData"
TRANSFORM_DATA_PATH = "/content/drive/MyDrive/Chotot Project/TransformData"

In [ ]:
import os
import json
import pandas as pd

# 1. Gom dữ liệu mua bán "s" cho tất cả các loại bất động sản

In [ ]:
subset_list = [
    "chotot_st_s_cg_1010/chotot_st_s_cg_1010_20251224_010402.json",
    "chotot_st_s_cg_1020/chotot_st_s_cg_1020_20251224_011615.json",
    "chotot_st_s_cg_1030/chotot_st_s_cg_1030_20251224_011638.json",
    "chotot_st_s_cg_1040/chotot_st_s_cg_1040_20251224_011907.json",
]

In [ ]:
all_data = []
for subset_path in subset_list:
  path = os.path.join(RAW_DATA_PATH, subset_path)
  with open(path) as f:
    data = json.load(f)
    all_data.extend(data)

In [ ]:
s_df = pd.DataFrame(all_data)

In [ ]:
print(len(s_df))
s_df.head()

30284

,account_id,account_name,account_oid,ad_features,ad_id,ad_labels,apartment_type,area,area_name,area_v2,...,house_type,length,living_size,streetnumber_display,width,property_road_condition,street_id,commercial_type,land_type,size_unit
0,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,[],172999910,[],1.0,115,Huyện Bình Chánh,13115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,663094,dang tuong vy,3fa9649369097f86c8ef3daa0555b546,[],173153112,[],1.0,119,Thành phố Thủ Đức,13119,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,[],172904394,[],1.0,115,Huyện Bình Chánh,13115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2884428,Đoàn minh hùng,5e89582abe33e6371f3b07b557813962,[],173153019,[],1.0,103,Quận 8,13103,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,[],171313066,[],1.0,115,Huyện Bình Chánh,13115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for column in s_df.columns:
  print(column)

account_id
account_name
account_oid
ad_features
ad_id
ad_labels
apartment_type
area
area_name
area_v2
avatar
body
business_days
category
category_name
company_ad
contain_videos
date
detail_address
fee_type
full_name
furnishing_sell
image
image_thumbnails
images
inspection_images
is_block_similar_ads_other_agent
is_sticky
is_zalo_show
label_campaigns
latitude
list_id
list_time
location
longitude
number_of_images
orig_list_time
params
price
price_million_per_m2
price_string
project_oid
projectid
property_legal_document
property_status
protection_entitlement
pty_characteristics
pty_jupiter
pty_map
pty_map_modifier
pty_project_name
region
region_name
region_name_v3
region_v2
rooms
seller_info
size
size_unit_string
sold_ads
special_display
special_display_images
specific_service_offered
state
status
stickyad_feature
street_name
subject
thumbnail_image
toilets
type
unitnumber_display
videos
ward
ward_name
ward_name_v3
webp_image
average_rating
average_rating_for_seller
floornumber
total_rating
total_rating_for_seller
unitnumber
balconydirection
is_main_street
location_id
unique_street_id
direction
block
has_video
shop
shop_alias
street_number
apartment_feature
projectimages
address
sticky_ad_type
phone_hidden
floors
house_type
length
living_size
streetnumber_display
width
property_road_condition
street_id
commercial_type
land_type
size_unit

In [ ]:
remove_fields = [
    "ad_features",
    "ad_id",
    "ad_labels",
    "avatar",
    "business_days",
    "date",
    "inspection_images",
    "label_campaigns",
    "params",
    "pty_characteristics",
    "specific_service_offered",
    "is_zalo_show",
    "seller_info",
    "is_sticky",
    "shop",
    "shop_alias",
    "projectimages",
    "phone_hidden",
]

In [ ]:
s_df = s_df.drop(columns=remove_fields)

In [ ]:
s_df.head()

,account_id,account_name,account_oid,apartment_type,area,area_name,area_v2,body,category,category_name,...,house_type,length,living_size,streetnumber_display,width,property_road_condition,street_id,commercial_type,land_type,size_unit
0,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,1.0,115,Huyện Bình Chánh,13115,"⭐ Giá bán: 3,65 tỷ (Bao full thuế phí)\n⭐ Diện...",1010,Căn hộ/Chung cư,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,663094,dang tuong vy,3fa9649369097f86c8ef3daa0555b546,1.0,119,Thành phố Thủ Đức,13119,Origami. Vinhome grand park q9\n1pn.chính chu ...,1010,Căn hộ/Chung cư,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,1.0,115,Huyện Bình Chánh,13115,"🏡 Bán căn hộ 113m² - Giá bán 4,44 tỷ - Ban côn...",1010,Căn hộ/Chung cư,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2884428,Đoàn minh hùng,5e89582abe33e6371f3b07b557813962,1.0,103,Quận 8,13103,"✅Dt: 45,3m2.Thiết kế 1PN, 1WC, phòng khách, bế...",1010,Căn hộ/Chung cư,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,1.0,115,Huyện Bình Chánh,13115,Căn hộ 2PN 2WC. Diện tích: 59m² (TT 54.5m²).\n...,1010,Căn hộ/Chung cư,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
s_df.to_csv(
    os.path.join(TRANSFORM_DATA_PATH, "s_listing.csv"),
    index=False
)

In [ ]:
for col, dtype in s_df.dtypes.items():
    print(f"{col}: {dtype}")

account_id: int64
account_name: object
account_oid: object
apartment_type: float64
area: int64
area_name: object
area_v2: int64
body: object
category: int64
category_name: object
company_ad: object
contain_videos: int64
detail_address: object
fee_type: object
full_name: object
furnishing_sell: float64
image: object
image_thumbnails: object
images: object
is_block_similar_ads_other_agent: object
latitude: float64
list_id: int64
list_time: int64
location: object
longitude: float64
number_of_images: int64
orig_list_time: float64
price: int64
price_million_per_m2: float64
price_string: object
project_oid: object
projectid: float64
property_legal_document: float64
property_status: float64
protection_entitlement: bool
pty_jupiter: int64
pty_map: object
pty_map_modifier: float64
pty_project_name: object
region: int64
region_name: object
region_name_v3: object
region_v2: int64
rooms: float64
size: float64
size_unit_string: object
sold_ads: float64
special_display: object
special_display_images: object
state: object
status: object
stickyad_feature: object
street_name: object
subject: object
thumbnail_image: object
toilets: float64
type: object
unitnumber_display: float64
videos: object
ward: int64
ward_name: object
ward_name_v3: object
webp_image: object
average_rating: float64
average_rating_for_seller: float64
floornumber: float64
total_rating: float64
total_rating_for_seller: float64
unitnumber: object
balconydirection: float64
is_main_street: object
location_id: object
unique_street_id: object
direction: float64
block: object
has_video: object
street_number: object
apartment_feature: float64
address: object
sticky_ad_type: object
floors: float64
house_type: float64
length: float64
living_size: float64
streetnumber_display: float64
width: float64
property_road_condition: float64
street_id: float64
commercial_type: float64
land_type: float64
size_unit: float64

#2. Gom dữ liệu cho thuê "u" cho tất cả các loại bất động sản

In [ ]:
subset_list = [
    "chotot_st_u_cg_1010/chotot_st_u_cg_1010_20251224_005052.json",
    "chotot_st_u_cg_1020/chotot_st_u_cg_1020_20251224_005441.json",
    "chotot_st_u_cg_1030/chotot_st_u_cg_1030_20251224_005727.json",
    "chotot_st_u_cg_1040/chotot_st_u_cg_1040_20251224_005733.json",
    "chotot_st_u_cg_1050/chotot_st_u_cg_1050_20251224_010213.json",
]

In [ ]:
all_data = []
for subset_path in subset_list:
  path = os.path.join(RAW_DATA_PATH, subset_path)
  with open(path) as f:
    data = json.load(f)
    all_data.extend(data)

In [ ]:
len(all_data)

37882

In [ ]:
u_df = pd.DataFrame(all_data)

In [ ]:
u_df.head()

,account_id,account_name,account_oid,ad_features,ad_id,ad_labels,apartment_type,area,area_name,area_v2,...,floors,length,living_size,streetnumber_display,width,property_road_condition,commercial_type,condition_ad,land_type,size_unit
0,23682325,Nguyen Phu,2414131cfd344c98d0e0573ce191a488,[],167055575,"[{'aspect_ratio': 4, 'campaign_marketing_id': ...",1.0,109,Quận Bình Thạnh,13109,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,[],168840429,[],1.0,115,Huyện Bình Chánh,13115,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,[],163399160,[],1.0,99,Quận 4,13099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,[],154489991,[],6.0,99,Quận 4,13099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,[],155948967,[],1.0,99,Quận 4,13099,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
for col, dtype in u_df.dtypes.items():
    print(f"{col}: {dtype}")

account_id: int64
account_name: object
account_oid: object
ad_features: object
ad_id: int64
ad_labels: object
apartment_type: float64
area: int64
area_name: object
area_v2: int64
avatar: object
average_rating: float64
average_rating_for_seller: float64
body: object
business_days: object
category: int64
category_name: object
company_ad: object
contain_videos: int64
date: object
fee_type: object
full_name: object
has_video: object
image: object
image_thumbnails: object
images: object
inspection_images: object
is_main_street: object
is_sticky: bool
is_zalo_show: object
label_campaigns: object
latitude: float64
list_id: int64
list_time: int64
location: object
location_id: object
longitude: float64
number_of_images: int64
params: object
price: int64
price_million_per_m2: float64
price_string: object
property_legal_document: float64
protection_entitlement: bool
pty_characteristics: object
pty_jupiter: int64
pty_map: object
pty_map_modifier: float64
pty_project_name: object
region: int64
region_name: object
region_name_v3: object
region_v2: int64
rooms: float64
seller_info: object
shop: object
shop_alias: object
size: float64
size_unit_string: object
sold_ads: float64
special_display_images: object
specific_service_offered: object
state: object
status: object
street_name: object
subject: object
thumbnail_image: object
toilets: float64
total_rating: float64
total_rating_for_seller: float64
type: object
unique_street_id: object
videos: object
ward: float64
ward_name: object
ward_name_v3: object
webp_image: object
balconydirection: float64
deposit: float64
detail_address: object
direction: float64
furnishing_sell: float64
is_good_room: object
project_oid: object
projectid: float64
street_number: object
unitnumber_display: float64
apartment_feature: float64
block: object
floornumber: float64
unitnumber: object
orig_list_time: float64
is_block_similar_ads_other_agent: object
special_display: object
sticky_ad_type: object
stickyad_feature: object
address: object
street_id: float64
phone_hidden: object
projectimages: object
furnishing_rent: float64
house_type: float64
floors: float64
length: float64
living_size: float64
streetnumber_display: float64
width: float64
property_road_condition: float64
commercial_type: float64
condition_ad: float64
land_type: float64
size_unit: float64

In [ ]:
remove_fields = [
    "ad_features",
    "ad_id",
    "ad_labels",
    "avatar",
    "business_days",
    "date",
    "inspection_images",
    "label_campaigns",
    "params",
    "pty_characteristics",
    "specific_service_offered",
    "is_zalo_show",
    "seller_info",
    "is_sticky",
    "shop",
    "shop_alias",
    "projectimages",
    "phone_hidden",
]

In [ ]:
u_df = u_df.drop(columns=remove_fields)

In [ ]:
u_df.head()

,account_id,account_name,account_oid,apartment_type,area,area_name,area_v2,average_rating,average_rating_for_seller,body,...,floors,length,living_size,streetnumber_display,width,property_road_condition,commercial_type,condition_ad,land_type,size_unit
0,23682325,Nguyen Phu,2414131cfd344c98d0e0573ce191a488,1.0,109,Quận Bình Thạnh,13109,4.9,4.7,"VT: Đường Điện Biên Phủ, Bình Thạnh\n💵 Giá chỉ...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,15769554,Minh Hiếu,b8abd37007704fd2ca7a0948d19ecb74,1.0,115,Huyện Bình Chánh,13115,NaN,NaN,🏡 Căn hộ 2PN – 2WC – Diện tích: 59m²\n\n✅ An n...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,1.0,99,Quận 4,13099,5.0,5.0,"⭕️𝐑𝐨̂̉ 𝐜𝐚̆𝐧 𝐒𝐚𝐢𝐠𝐨𝐧 𝐑𝐨𝐲𝐚𝐥-𝐒𝐭𝐮𝐝𝐢𝐨 𝟏𝟐𝐭𝐫,𝟏𝐏𝐍 𝟏𝟔𝐭𝐫,...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,6.0,99,Quận 4,13099,5.0,5.0,"⭕️ 𝗦𝗮𝗶𝗴𝗼𝗻 𝗥𝗼𝘆𝗮𝗹 𝗥𝗲𝘀𝗶𝗱𝗲𝗻𝗰𝗲 - 𝗦𝘁𝘂𝗱𝗶𝗼 - 𝟭𝟐,𝟓 𝗧𝗿𝗶𝗲...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,11845737,Yến Lê,5cc517992cbfb50a5fe04dc2b653be7f,1.0,99,Quận 4,13099,5.0,5.0,"⭕️𝐑𝐨̂̉ 𝐜𝐚̆𝐧 𝐌𝐢𝐥𝐥𝐞𝐧𝐧𝐢𝐮𝐦 - 𝐒𝐭𝐮𝐝𝐢𝐨 𝟏𝟏𝐭𝐫, 𝟏𝐏𝐍 𝟏𝟕 𝐓...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
u_df.to_csv(
    os.path.join(TRANSFORM_DATA_PATH, "u_listing.csv"),
    index=False
)

In [ ]:
for col, dtype in u_df.dtypes.items():
    print(f"{col}: {dtype}")

account_id: int64
account_name: object
account_oid: object
apartment_type: float64
area: int64
area_name: object
area_v2: int64
average_rating: float64
average_rating_for_seller: float64
body: object
category: int64
category_name: object
company_ad: object
contain_videos: int64
fee_type: object
full_name: object
has_video: object
image: object
image_thumbnails: object
images: object
is_main_street: object
latitude: float64
list_id: int64
list_time: int64
location: object
location_id: object
longitude: float64
number_of_images: int64
price: int64
price_million_per_m2: float64
price_string: object
property_legal_document: float64
protection_entitlement: bool
pty_jupiter: int64
pty_map: object
pty_map_modifier: float64
pty_project_name: object
region: int64
region_name: object
region_name_v3: object
region_v2: int64
rooms: float64
size: float64
size_unit_string: object
sold_ads: float64
special_display_images: object
state: object
status: object
street_name: object
subject: object
thumbnail_image: object
toilets: float64
total_rating: float64
total_rating_for_seller: float64
type: object
unique_street_id: object
videos: object
ward: float64
ward_name: object
ward_name_v3: object
webp_image: object
balconydirection: float64
deposit: float64
detail_address: object
direction: float64
furnishing_sell: float64
is_good_room: object
project_oid: object
projectid: float64
street_number: object
unitnumber_display: float64
apartment_feature: float64
block: object
floornumber: float64
unitnumber: object
orig_list_time: float64
is_block_similar_ads_other_agent: object
special_display: object
sticky_ad_type: object
stickyad_feature: object
address: object
street_id: float64
furnishing_rent: float64
house_type: float64
floors: float64
length: float64
living_size: float64
streetnumber_display: float64
width: float64
property_road_condition: float64
commercial_type: float64
condition_ad: float64
land_type: float64
size_unit: float64